### ISSUE TITLE
api extension - List of holiday dates in the next x days

### ISSUE THREAD

**Issue by rolero** [tinohager/Nager.Date#101]
### Important specifications

* Which country is affected? All
* If you have found a mistake please also provide a valid source of your information?

For more information, see the `CONTRIBUTING` guide.

### Description

Is it possible to have an API and view that list all the events (including detailed data) for the next x days for all counties or a list of countries. That would be a great addition to this solution

**Comment by tinohager** [comment]
Can you check this new version?
https://beta.date.nager.at/swagger/index.html

**Comment by tinohager** [comment]
the new api is available
