### ISSUE TITLE
Bank/school closing dates in Denmark

### ISSUE THREAD

**Issue by CasperWSchmidt** [tinohager/Nager.Date#104]
### Important specifications

* Which country is affected? DK/Denmark
* If you have found a mistake please also provide a valid source of your information?
http://www.nationalbanken.dk/da/Kontakt/aabningstider/Sider/default.aspx - box on the right (in danish)

For more information, see the `CONTRIBUTING` guide.

### Description

In Denmark banks and schools are closed on friday after Ascension Day (easter sunday+39), but it is not a public holiday (ie. not a paid day off outside banking and schools). A lot of people do take the days off though :)
The same goes for December 24. and 31. They are not public holidays but banks and schools are closed and often these days are included as holidays in the union agreement between employers and empoyees. Only supermarkets, hospitals and other emergency services are open these days (supermarkets usually only until 12pm on the 24. and until 4pm on the 31.).
Also banks are closed on June 5. (Constitution Day) but this is not a public holiday either. Most people do have the day of on May 1. (International Workers' Day/Labor day) OR June 5. though.

I don't know the best way to implement this?

**Comment by tinohager** [comment]
I think we can use for this the type field. https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/Model/PublicHolidayType.cs

**Comment by CasperWSchmidt** [comment]
That was my thought as well, but if it both a closing day for banks and schools should it be included twice with different types in the collection?

**Comment by CasperWSchmidt** [comment]
Ah I missed that! Thanks :)

I will make a Pull Request later.

**Comment by CasperWSchmidt** [comment]
I just created a pull request. When merged I will get the newest nuget package and start using your nice library for our financial system :)

**Comment by tinohager** [comment]
New package is published, In which financial system will be used in the future?

**Comment by CasperWSchmidt** [comment]
An internal system for the company I work for (Hemonto).
