### ISSUE TITLE
Missing holidays in Victoria, Australia

### ISSUE THREAD

**Issue by otravers** [tinohager/Nager.Date#107]
### Important specifications

* Country is affected: Australia, VIC
* Valid source of your information: http://www.business.vic.gov.au/victorian-public-holidays-and-daylight-saving/victorian-public-holidays

### Description

Thanks for this useful API. In the state of Victoria you're missing two sports-related public holidays: 1) Friday before the AFL Grand Final, and 2) Melbourne Cup.

The AFL holiday was introduced in 2015:
https://www.theage.com.au/national/victoria/afl-grand-final-daniel-andrews-upbeat-about-new-public-holiday-despite-interstate-threat-20150913-gjlcv9.html

Melbourne Cup has been a public holiday since 1877:
- https://publicholidays.com.au/melbourne-cup-day/
- https://www.prov.vic.gov.au/index.php/about-us/our-blog/why-melbourne-cup-day-public-holiday

**Comment by otravers** [comment]
I don't know, I'm not Australian and I don't follow their sports! It's just that I have a client there.  I've googled it but didn't find anything definitive, maybe the AFL themselves could give you some insight into how it's set each year?

**Comment by tinohager** [comment]
An other project have also no calculation for this day. I can only add public holidays with a formula.
https://github.com/holidays/holidays/blob/c2463483d1289c6b5a493a5de8dab0256ff4436f/lib/generated_definitions/au.rb

**Comment by Shaenn** [comment]
Hi @otravers 
I'm writing a C# library (4.6.2 and netStandard 2.0) on holidays and I can handle your demand.
See an example of kind you can write, and can interprete, with my dll :
**ExpressionTree.Date.MovableFromMovable( Count.First, DayOfWeek.Friday ).Before( Count.First, DayOfWeek.Saturday ).Before( Month.October );**
You can read this "The friday before the first saturday before the 01 october" and is it "the day before the last saturday in september"

enjoy, good evening !

Shaenn

**Comment by Adnett10123** [comment]
@tinohager Can these two Holidays be added to the API?

**Comment by tinohager** [comment]
@Adnett10123 we have not found a documentation.
