### ISSUE TITLE
Labour Day in NSW, Australia is incorect

### ISSUE THREAD

**Issue by JohnGreenhow** [tinohager/Nager.Date#108]
### Important specifications

* Australia (NSW)
* Source of data used by Australian government:  http://www.industrialrelations.nsw.gov.au/oirwww/NSW_public_holidays/NSW_Public_Holidays.page

### Description
Current page for Australia shows Labour Day for NSW as 8/6/2018.   Labour Day this year is Monday 1st October 2018 and in general it is the 1st Monday of October.

**Comment by JohnGreenhow** [comment]
Although there's no entry for the state, it is in the per-holiday section already.

I can see an entry in Wikipedia here: https://en.wikipedia.org/wiki/Public_holidays_in_Australia#Labour_Day

To quote (emphasis mine):

"The Labour Day public holiday varies considerably between the various states and territories<https://en.wikipedia.org/wiki/States_and_territories_of_Australia>. It is the first Monday in October in the Australian Capital Territory<https://en.wikipedia.org/wiki/Australian_Capital_Territory>, New South Wales<https://en.wikipedia.org/wiki/New_South_Wales> and South Australia<https://en.wikipedia.org/wiki/South_Australia>. In Western Australia<https://en.wikipedia.org/wiki/Western_Australia>, it is the first Monday in March. In both Victoria<https://en.wikipedia.org/wiki/Victoria_(Australia)> and Tasmania<https://en.wikipedia.org/wiki/Tasmania>, it is the second Monday in March. In the Northern Territory<https://en.wikipedia.org/wiki/Northern_Territory> and Queensland<https://en.wikipedia.org/wiki/Queensland>,[2]<https://en.wikipedia.org/wiki/Public_holidays_in_Australia#cite_note-pubholqld-2> it is the first Monday in May."

The holiday is also covered in the main coloured chart at the top of the page.

I think the state specific sections are intended to refer just to any state-specific exceptions, rather than the rule.

Regards,
John

________________________________

**Comment by JohnGreenhow** [comment]
So the code looks correct:

`items.Add(new PublicHoliday(firstMondayInAugust, "Labour Day", "Labour Day", countryCode, null, new string[] { "AUS-ACT", "AUS-NSW", "AUS-SA" }));
`
It must just be the website itself?

**Comment by tinohager** [comment]
``items.Add(new PublicHoliday(firstMondayInOctober, "Labour Day", "Labour Day", countryCode, null, new string[] { "AUS-ACT", "AUS-NSW", "AUS-SA" }));``

[commit with the fix](https://github.com/tinohager/Nager.Date/commit/f43d20385c9df815cc6004b1ae19af7a0f908c33)

**Comment by JohnGreenhow** [comment]
Quick fix, awesome!
