### ISSUE TITLE
DateTimeExtension.IsWeekend does not handle non Universal weekends

### ISSUE THREAD

**Issue by xlecoustillier** [tinohager/Nager.Date#109]
Hi, thanks for this nice library.

Looking at the source code, I notice that [IsWeekend ](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/Extensions/DateTimeExtension.cs) does not handle not universal weekends, even if almost every needed info is provided (country code and link to the relevant wikipedia page).

Is it because of lack of time, or do you see other problems (specific ways of handling weekends, in India for instance) ?

**Comment by tinohager** [comment]
lack of time :construction_worker: 😀

**Comment by xlecoustillier** [comment]
Closing following #113 merge.
Thanks!

**Comment by tinohager** [comment]
You are welcome
