### ISSUE TITLE
Public & Religious Holidays

### ISSUE THREAD

**Issue by 51tharea** [tinohager/Nager.Date#111]
Hi, thank you for share your lib.
Could you add  Religious Holidays for the country?
Example: 
Country: Turkey

There are 2 two different  Religious Holidays, for example, Ramadan, Sacrifice Feast

https://www.timeanddate.com/holidays/turkey/

**Comment by tinohager** [comment]
Sorry Ramadan is not calculable it dependent on the moon. (The calendar is a lunar calendar, and months begin when the first crescent of a new moon is sighted)
