### ISSUE TITLE
[Germany Provider] Hamburg - Reformation Day

### ISSUE THREAD

**Issue by ewolution94** [tinohager/Nager.Date#112]
### Important specifications

* Germany - Hamburg
* https://www.ndr.de/nachrichten/hamburg/Hamburg-hat-einen-neuen-Feiertag,feiertag232.html
* https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland#%C3%9Cbersicht_aller_gesetzlichen_Feiertage

### Description

Currently, Reformation Day for Hamburg is added based on 'year==2017' condition. Please make it a general holiday for Hamburg. Can be confirmed with the provided links.

**Comment by tinohager** [comment]
I have add the fix https://github.com/tinohager/Nager.Date/commit/b843ebae5b0413497a0e55256a6caa4be0e177e7
