### ISSUE TITLE
Wrong translations in CzechRepublic holidays

### ISSUE THREAD

**Issue by Mika5652** [tinohager/Nager.Date#118]
### Important specifications

* Czech Republic
* http://svatky.najdise.cz/statni-svatky-2018

### Description

You have wrong naming holidays in czech language. Concrete in 8. May and, there you have only "Den vítězství or Den osvobození", but should be "Den vítězství - Den osvobození od fašismu".
Next wrong translation is from "Easter Sunday", there you have only "Velikonoční", but should be "Velikonoční neděle".

**Comment by tinohager** [comment]
Thanks for the info have you a better source for the informations? wikipedia or goverment page?

**Comment by Mika5652** [comment]
I am from Czech Republic. There is more sources for example you can look into https://publicholidays.cz/cs/2018-dates/ .
