### ISSUE TITLE
Add country "Albania"

### ISSUE THREAD

**Issue by Silvio911** [tinohager/Nager.Date#119]
### https://en.wikipedia.org/wiki/Public_holidays_in_Albania

**Comment by prasadtelkikar** [comment]
@Silvio911, I would like to add country "Albania", need your clarification before I start writing code.
Is Jan 1 - Jan 2 both are holidays in Albania?
**All dates are constant or varies every year?**
Do we need to include Not official holidays as well? if yes then again same question all dates are constants or varies every year?

**Comment by laloune** [comment]
just for my information, how do you plan to set the dates for Eid ul-Fitr and Eid ul-Adha ? the wikipedia page says that it varies (and I have the impression that the official date is known only a couple of days before)

**Comment by Silvio911** [comment]
Jan 1 - Jan 2 are both holidays(New year days).
Regarding  religious holidays(exp. Eid ul-Fitr and Eid ul-Adha) you can't include them because they change every year.

**Comment by erjon03** [comment]
any news about this issue?

**Comment by tinohager** [comment]
@erjon03 Hi, this is an open source project and anyone can join in and you can contribute to Albania or Kosovo.

**Comment by prasadtelkikar** [comment]
@erjon03 ,
**Regarding Albania** : We have already added code for Albania country, you can look into source code.
**Regarding Kosovo**: As Kosovo is not an official assigned, so we disabled this country.

@tinohager , This issue has been resolved. We can close it. Let me know your thoughts on it.
