### ISSUE TITLE
Type of holidays in XML output

### ISSUE THREAD

**Issue by laloune** [tinohager/Nager.Date#121]
Hi,

would this be possible to get in the XML output also the type (Public, Bank, School, Optional...)

I am currently trying to build the country provider for Hong Kong and this would be really helpful since some public holidays are non-statutory (thus should be flagged as "Optional")

Thanks!

laloune

**Comment by tinohager** [comment]
Yes i must change the api, currently i am busy maybe i found time the next weeks

**Comment by laloune** [comment]
Hello,

any news about this topic ?

thanks!
laloune

**Comment by tinohager** [comment]
I am work on a new version of website and on this release also a new api is available, please have a little patience.

**Comment by laloune** [comment]
will do. Thanks a bunch!

**Comment by tinohager** [comment]
Can you check this new version?
https://beta.date.nager.at/swagger/index.html

**Comment by tinohager** [comment]
The new api is available
