### ISSUE TITLE
System.TypeInitializationException on Nager.Date.DateSystem

### ISSUE THREAD

**Issue by Cutyno** [tinohager/Nager.Date#123]
### Important specifications

* Which country is affected?
>The bug concerned only Japan but affected all containing countries.
* If you have found a mistake please also provide a valid source of your information?

### Description

As I updated from Nuget 1.22.4 to 1.24.0, I got prompted with an System.TypeInitializationException on Nager.Date.DateSystem. Apparently the type initializer for 'Nager.Date.DateSystem' threw an exception. As an Exception I got: 
> System.TypeInitializationException: The type initializer for 'Nager.Date.DateSystem' threw an exception. 
> ---> System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
> at System.TimeZoneInfo.FindSystemTimeZoneByIdCore (System.String id) [0x00007] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
> at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00021] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
> at Nager.Date.PublicHolidays.JapanProvider..ctor () [0x00006] in <5a1524b3438045359825b38d389f7ca1>:0
> at Nager.Date.DateSystem..cctor () [0x00412] in <5a1524b3438045359825b38d389f7ca1>:0
  --- End of inner exception stack trace ---

As far as I could narrow down the bug, it only affects the versions including 1.23.0

**Comment by tinohager** [comment]
Can you try this code on your system?

    var test = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");

**Comment by tinohager** [comment]
Which Enviorment you are use? Windows, Linux, Mac, .net core?

**Comment by Cutyno** [comment]
I use your code inside a Xamarin App and tested it on an Android Emulator. From there I got the Error. 
As far as I understand I'm the only one getting this problem. If i can find some time I try to download your repo (don't use nuget) and try to find the problem and maybe try to come up with a solution.

**Comment by tinohager** [comment]
You are use an older Android Version 7.1? https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.findsystemtimezonebyid?view=netframework-4.7.2

**Comment by Cutyno** [comment]
Yeah you're right. I'm using Android 4.3 and newer but my target is Android 9.0.
But I guess it's only part of the problem. All other countries are just fine. The problem occurs after and just with the japan provider.

**Comment by tinohager** [comment]
I have publish a new package with a fix

**Comment by Cutyno** [comment]
Thank you for the fix!
This solves my problem. Nice work!
