### ISSUE TITLE
Dutch holidays

### ISSUE THREAD

**Issue by MachteldTC** [tinohager/Nager.Date#129]
Sorry, hadn't noticed it was just the title.

Country = The Netherlands (NL)
Government website explaining it all = https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/officiele-feestdagen

Good Friday is not Public in NL, it's only Schools and Authorities
Liberation Day in NL is only Public once every 5 years (2020 is the next one), the other years it's only Schools and Authorities.

**Comment by tinohager** [comment]
Can you check my update?
