### ISSUE TITLE
Split UK

### ISSUE THREAD

**Issue by mtpilarek** [tinohager/Nager.Date#130]
England and Wales, Scotland, Northern Wales all have different holidays, but in CountryCode I can only find GB as a whole, what is very annoying, because it merges all into one making it quite useless.

It would be great if you could split GB into 3 different ones like below:
https://www.gov.uk/bank-holidays.json

**Comment by laloune** [comment]
actually you can get the information from the Counties - that is how it works for all the countries where the public holidays are not country-wide (e.g. Germany)

**Comment by mtpilarek** [comment]
I know, but I think that it would be helpful for a lot of people to make an exception and split it for UK. 
It's quite small change, which would make your library much more useful.

**Comment by tinohager** [comment]
We have the option to add counties on every public holiday.
https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/SwitzerlandProvider.cs

Splitting into own providers I find a bad idea. Is the county option not possible for you?

**Comment by mtpilarek** [comment]
Ow I missed this option. You should write something about this on the main page, because you either have to see the structure of PublicHoliday object or when someone looks into the source it's on far right in the providers' files so it's also easily missed.

**Comment by tinohager** [comment]
I try to optimize my documentation.

**Comment by tinohager** [comment]
Is this enough? https://github.com/tinohager/Nager.Date/blob/master/README.md#get-all-publicholidays-of-a-country-and-year

**Comment by mtpilarek** [comment]
Yes, that's enough. I think it will make much less confusion in future for anyone looking into your github. Thank You for help.
