### ISSUE TITLE
Consistent arguments

### ISSUE THREAD

**Issue by ptrkrlsrd** [tinohager/Nager.Date#131]
### Make the arguments in the methods consistent

The API would be more intuitive to use if the arguments were ordered consistently. In my case I found that `IsPublicHoliday` takes the date as the first parameter, and CountryCode as the last. To me this makes sense since the date is the "most important" value, and thereafter the country. While in `GetLongWeekend` the country code comes first and then the year. This feels unatural and is different from the previous example.

### Description
``` csharp
var date = DateTime.Now;
bool isPublicHoliday = DateSystem.IsPublicHoliday(date, CountryCode.NO);
IEnumerable<LongWeekend> weekends = DateSystem.GetLongWeekend(CountryCode.NO, year);
```

**Comment by tinohager** [comment]
Can you check my changes, if it now okay?

**Comment by ptrkrlsrd** [comment]
Hey, yes this looks a lot better! Think this will make the package a little easier to use :+1:
