### ISSUE TITLE
Canada/Quebec Corrections

### ISSUE THREAD

**Issue by FlaveC** [tinohager/Nager.Date#132]
* Which country is affected?
Canada

There are two correction that should be made for the Quebec entries in  in CanadaProvider.cs:

Include CA-QC for Easter Monday:
    items.Add(new PublicHoliday(easterSunday.AddDays(1), "Easter Monday", "Easter Monday", countryCode, null, new string[] { "CA-AB", "CA-PE" }));
should be
    items.Add(new PublicHoliday(easterSunday.AddDays(1), "Easter Monday", "Easter Monday", countryCode, null, new string[] { "CA-AB", "CA-PE", "CA-QC" }));

Add St. Jean Baptist CA-QC holiday:	
    items.Add(new PublicHoliday(year, 6, 24, "Discovery Day", "Discovery Day", countryCode, null, new string[] { "CA-NL", "CA-QC", "CA-YT" }));
Should be:
    items.Add(new PublicHoliday(year, 6, 24, "Discovery Day", "Discovery Day", countryCode, null, new string[] { "CA-NL", "CA-YT" }));
    items.Add(new PublicHoliday(year, 6, 24, "Fête de la Saint-Jean-Baptiste", "Fête de la Saint-Jean-Baptiste", countryCode, null, new string[] { "CA-QC" }));

**Comment by tinohager** [comment]
Is the information on wikipedia wrong?
https://en.wikipedia.org/wiki/Public_holidays_in_Canada

![image](https://user-images.githubusercontent.com/8215186/52819594-f46e8200-30a9-11e9-9761-676ddeddb1fb.png)

**Comment by FlaveC** [comment]
Yes and no. The problem is that Quebec gives companies the option of giving their employees either Good Friday OR Easter Monday off. So either can be a holiday depending on the company you work for.

**Comment by tinohager** [comment]
A company option is not a public holiday in my opinion. A public holiday is free for all, if the company decides it is a bonus.
