### ISSUE TITLE
Add out parameter for IsPublicHoliday calls

### ISSUE THREAD

**Issue by FlaveC** [tinohager/Nager.Date#133]
It would be useful if the IsPublicHoliday call had an additional variant that included an "out" parameter returning the first PublicHoliday in the enumerable. For instance:

public static bool IsPublicHoliday(DateTime date, CountryCode countryCode, out PublicHoliday publicHoliday)
{
var items = GetPublicHoliday(date.Year, countryCode);
publicHoliday = items.FirstOrDefault(o => o.Date.Date == date.Date);
return publicHoliday != null;
}

public static bool IsOfficialPublicHolidayByCounty(DateTime date, CountryCode countryCode, string countyCode, out PublicHoliday publicHoliday)
{
var items = GetPublicHoliday(date.Year, countryCode);
publicHoliday = items.FirstOrDefault(o => o.Date.Date == date.Date && (o.Counties == null || o.Counties.Contains(countyCode)));
return publicHoliday != null;
}

**Comment by tinohager** [comment]
Is this a good implementation for you?
https://github.com/tinohager/Nager.Date/commit/22c058bd811a01b21bcbf835d2049d07f04782d6
