### ISSUE TITLE
Correct local names on Swedish public holidays

### ISSUE THREAD

**Issue by peru62** [tinohager/Nager.Date#144]
### Important specifications

* Which country is affected?
* If you have found a mistake please also provide a valid source of your information?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

**Comment by peru62** [comment]
Local names of Swedish public holidays are not correct. Please use standard names as in https://www.kalender.se/helgdagar (column Name)

**Comment by tinohager** [comment]
Can you check the changes? https://github.com/tinohager/Nager.Date/commit/a1ccbd5388ffb2b4bea2b126490ddccc25eb10e1

**Comment by tinohager** [comment]
It is possible on your source the name for "Kristi himmelsfärdsdag" is wrong without the `s`

**Comment by peru62** [comment]
Yes, you are right! It should be with the s: "Kristi himmelsfärdsdag"
