### ISSUE TITLE
Romania - Vinerea Mare is missing - last Friday before Orthodox Easter

### ISSUE THREAD

**Issue by ionaxenti** [tinohager/Nager.Date#145]
### Important specifications

This applies for Romania.

### Description

In Romania since 2018 (including) the last Friday before Orthodox Easter is national holiday. See
http://www.cdep.ro/pls/proiecte/docs/2018/pr068_18.pdf
In 2019 this is on 26th of April.

In Romania the local name is "Vinerea mare", in English it is "Good Friday". This is repeating every year since 2018.

Thanks,
Ion Axenti

**Comment by tinohager** [comment]
Thanks i have add the new day.

**Comment by ionaxenti** [comment]
Thanks Tino,

one remark: in 2017 and lower it shouldn't exist. It exists starting with 2018 (6th April).

Ion
