### ISSUE TITLE
New public holiday in Luxembourg

### ISSUE THREAD

**Issue by CasperWSchmidt** [tinohager/Nager.Date#147]
According to my contact in Luxembourg and https://luxtimes.lu/luxembourg/36056-when-are-luxembourg-public-holidays-in-2019 a new holiday has been added in Luxembourg this year.

I will make a PR as soon as I know the luxembourgish name of the new holiday.

**Comment by Mincka** [comment]
It is called "Europe Day" or "Europadag" in Luxembourgish.

http://luxembourg.public.lu/en/travailler/jours-feries-legaux/index.html
https://lb.wikipedia.org/wiki/Europadag

Pull request has been created #151

**Comment by tinohager** [comment]
Thanks
