### ISSUE TITLE
Alter May Day 2020 UK

### ISSUE THREAD

**Issue by philmacdonald2** [tinohager/Nager.Date#149]
### Important specifications

* Which country is affected? United Kingdom
* If you have found a mistake please also provide a valid source of your information?

Alteration of holiday location for 1 year only

### Description

The UK is moving the Early May Bank Holiday from Monday 4th May 2020 to Friday 8th May 2020, meaning this will need to be updated. It is a one-off change.

Source: [https://www.bbc.co.uk/news/uk-48565417](https://www.bbc.co.uk/news/uk-48565417)

**Comment by tinohager** [comment]
Thanks for the pull

**Comment by tinohager** [comment]
The new nuget package is pushed

**Comment by jemunk** [comment]
It is wrong implemented. See https://github.com/tinohager/Nager.Date/issues/153
