### ISSUE TITLE
Newest Nager.Date v1.5.0 Nuget package pulls in a ton of dependencies

### ISSUE THREAD

**Issue by MrCsabaToth** [tinohager/Nager.Date#15]
I'm not sure why is that, but when I updated to this newest 1.5 package depends on 
`.NETStandard, Version1.1`
`NETStandard.Library (>= 1.6.1)`

When installing, `<package id="NETStandard.Library" version="1.6.1" targetFramework="net461" />`
is added to my project, but as dependencies all of these packages are also pulled in, almost doubling my existing number of packages in my APS.NET MVC project:

    <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net461" />
    <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net461" />
    <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
    <package id="System.Collections" version="4.3.0" targetFramework="net461" />
    <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
    <package id="System.Console" version="4.3.0" targetFramework="net461" />
    <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
    <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net461" />
    <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
    <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net461" />
    <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
    <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net461" />
    <package id="System.IO" version="4.3.0" targetFramework="net461" />
    <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
    <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net461" />
    <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
    <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
    <package id="System.Linq" version="4.3.0" targetFramework="net461" />
    <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
    <package id="System.Net.Http" version="4.3.1" targetFramework="net461" />
    <package id="System.Net.Primitives" version="4.3.0" targetFramework="net461" />
    <package id="System.Net.Sockets" version="4.3.0" targetFramework="net461" />
    <package id="System.ObjectModel" version="4.3.0" targetFramework="net461" />
    <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
    <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net461" />
    <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net461" />
    <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
    <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
    <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net461" />
    <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
    <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
    <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net461" />
    <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
    <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
    <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net461" />
    <package id="System.Threading" version="4.3.0" targetFramework="net461" />
    <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
    <package id="System.Threading.Timer" version="4.3.0" targetFramework="net461" />
    <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net461" />
    <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />

This is crazy, I don't know why it's happening, but I could deal with it.
Actually one of these packages had an earlier version in my projects:
`<package id="System.Net.Http" version="4.0.0" targetFramework="net461" />`

Maybe the fact that that is needed to be `4.3.0` causes all of the other packages to be pulled in. `"NETStandard.Library" version="1.6.1"` requires that 4.3.0 System.Net.Http? I don't know what to do. Because after all of these packages installed, my project is throwing a mysterious exceptions:

    Exception thrown: 'System.MissingMethodException' in ThruThink.dll
    Additional information: Method not found: 'Void System.Web.Http.HttpResponseException..ctor(System.Net.Http.HttpResponseMessage)'.

I'm not blaming this on Nager.Date, but I wonder if there's a way to adjust the dependency so it won't pull in packages.

**Comment by tinohager** [comment]
Hi, i know i have update to visual studio 2017 and try the new project type .net standard but i not found any option to remove this dependencies. At the moment i suggest the 1.4 version.

**Comment by MrCsabaToth** [comment]
Good info. Since the fix is about Thanksgiving, which is some time away (November) I can downgrade, but now that you mention Visual Studio 2017 maybe I should install that and see if that solves the problem. There's another package too which started to do this, so I cannot resist forever, I need to figure out what's happening.

**Comment by MrCsabaToth** [comment]
VS 2017 install didn't help. Let's see if SO can come up with anything: https://stackoverflow.com/questions/42896662/why-method-not-found-void-system-web-http-httpresponseexception-ctor-after

**Comment by MrCsabaToth** [comment]
I don't know what you did, but upgrading to 1.5.1 is smooth. I don't have the problem above any more with that version. I'm very curious from package standpoint what is causing the 1.5.1 behave smooth vs the 1.5.0. Thanks!
