### ISSUE TITLE
GB: Wrong Early May Bank Holiday for 2020

### ISSUE THREAD

**Issue by jemunk** [tinohager/Nager.Date#153]
Regarding https://github.com/tinohager/Nager.Date/pull/150

Not working according to articles that says it is 8 May. 
https://www.theguardian.com/world/2019/jun/08/early-may-bank-holiday-2020-to-be-moved-to-coincide-with-ve-day

The code finds first Friday in May 2020 which ends up being 1 May!

**Comment by philmacdonald2** [comment]
Indeed, I made a mistake. I'll make a PR now to alter this.

**Comment by philmacdonald2** [comment]
@tinohager can you let me know when you release this?
