### ISSUE TITLE
1st of July is being considered a holiday in Portugal

### ISSUE THREAD

**Issue by tiagossa1** [tinohager/Nager.Date#163]
### Which country is affected?
Portugal.

### Description

This is really a cool package! I'm using it for a personal project and, generating the holidays for Portugal in July 2019, it gives me the 1st of July as a holiday, which isn't. The only country i know it's a holiday is Canada.

![Untitled](https://user-images.githubusercontent.com/39096494/62202797-de1b6080-b381-11e9-98b2-65a79b4e72fd.png)

**Comment by jduartedj** [comment]
This is not an error, it is a local holiday for Madeira.
You need to check the "Global" property to verify if it is national (true) or not (false)

**Comment by tinohager** [comment]
@tiagossa1 Can you check my update?

**Comment by tinohager** [comment]
[New version](https://www.nuget.org/packages/Nager.Date/1.25.4) is published
