### ISSUE TITLE
Carnival (Shrove Tuesday) should not be considered a National Holiday in Portugal

### ISSUE THREAD

**Issue by jduartedj** [tinohager/Nager.Date#165]
* Which country is affected?
Portugal

* If you have found a mistake please also provide a valid source of your information?
Shrove Tuesday is not an official National Holiday.

Source:
**[Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_Portugal)**
> Carnival in Portugal is an annual festival, that ends on Shrove Tuesday (called Fat Tuesday in Madeira - Terça-feira Gorda in Portuguese) the day before Ash Wednesday (first day of Lent). **This is an optional holiday**, although it is usually observed. 47 days before Easter Sunday.

**Note** that this is an optional holiday and usually it is not observed (unlike wikipedia says).

_Also I'm a good source of information since I'm Portuguese myself 😄_

**Comment by tinohager** [comment]
@jduartedj Can you check my update? Thanks

**Comment by jduartedj** [comment]
It doesn't seem to be working yet. To be Sure, global should be false, right?

![image](https://user-images.githubusercontent.com/350819/62458413-c1619d00-b774-11e9-9393-a521c8cc95c7.png)

**Comment by tinohager** [comment]
i have not publish the changes only in the code at the moment

https://github.com/tinohager/Nager.Date/commit/b050ca3198e2d3e0e86c48e7a6d2d740a790d125

**Comment by tinohager** [comment]
[New version](https://www.nuget.org/packages/Nager.Date/1.25.4) is published
