### ISSUE TITLE
Add support  for Public Holidays in Zimbabwe

### ISSUE THREAD

**Issue by Ed87** [tinohager/Nager.Date#166]
### Important specifications

* Which country is affected?
* If you have found a mistake please also provide a valid source of your information?

For more information, see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

**Comment by Ed87** [comment]
I want to implement the same for Zimbabwe. When can i expect support for ZW, or alternatively how do i edit the source myself to cater for Zimbabwe

**Comment by tinohager** [comment]
Source: https://en.m.wikipedia.org/wiki/Public_holidays_in_Zimbabwe

**Comment by tinohager** [comment]
@Ed87 Can you check my update? Thanks

**Comment by Ed87** [comment]
+1.  Is this updated with Nuget package as well

**Comment by tinohager** [comment]
[New version](https://www.nuget.org/packages/Nager.Date/1.25.4) is published
