### ISSUE TITLE
Corrected Czech and Slovak holidays

### ISSUE THREAD

**Issue by luke-kofer** [tinohager/Nager.Date#169]
### Important specifications

* Czech republic and Slovakia
* https://www.zakonyprolidi.cz/cs/2000-245
* https://www.zakonypreludi.sk/zz/1993-241

### Description

* Czech republic:
- remove **Velikonoční neděle**
- rename **Den vítězství - Den osvobození od fašismu** to **Den vítězství**
- rename **Den boje za svobodu a demokracii** to **Den boje za svobodu a demokracii a Mezinárodní den studentstva**

* Slovakia:
- rename **Veľkonočný piatok** to **Veľký piatok**
- rename **Sviatok svätého Cyrila a Metoda** to **Sviatok svätého Cyrila a svätého Metoda**
- rename **Sviatok Panny Márie Sedembolestnej** to **Sedembolestná Panna Mária**
- rename **Sviatok všetkých svätých** to **Sviatok Všetkých svätých**

**Comment by tinohager** [comment]
My Information source is wikipedia is this Informations are invalid?
- https://en.wikipedia.org/wiki/Public_holidays_in_Slovakia
- https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic

Source Code:

- [CzechRepublicProvider](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/CzechRepublicProvider.cs)
- [SlovakiaProvider](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/SlovakiaProvider.cs)

**Comment by luke-kofer** [comment]
1. remove: Wikipedia also not contains "Velikonoční neděle" ("Easter Sunday") in Czech republic holidays.
2. rename: Other comments only contain more precise actual names by state law (links in previous comment).
