### ISSUE TITLE
[Germany Provider] Thuringia - World Children's Day

### ISSUE THREAD

**Issue by Atvaark** [tinohager/Nager.Date#171]
### Important specifications
Key            | Value
--------- | ------------
Country - County | Germany - Thüringen (DE-TH)
Date      |  20 September
Starting Year | 2019
Local Name    | Weltkindertag
English Name  | World Children's Day

### Description

Sources:
https://en.wikipedia.org/wiki/Public_holidays_in_Germany
https://www.thueringer-landtag.de/service/presse/pressemitteilungen/weltkindertag-am-20-september-wird-gesetzlicher-feiertag/

**Comment by Atvaark** [comment]
Thanks.

v1.25.5 doesn't handle the starting year correctly.
- DateSystem.IsOfficialPublicHolidayByCounty returns true for September 20, DE-TH and years < 2019.
- GetPublicHoliday(DateTime startDate, DateTime endDate, string countryCode) also returns PublicHoliday instances with Date < 2019

   ```
     [TestMethod]
        public void TestGermanyIsOfficialPublicHolidayByCountyWithCountySpecificWorldChildrensDay()
        {
            var isPublicHolidayInTH2018 = DateSystem.IsOfficialPublicHolidayByCounty(new DateTime(2018, 9, 20), CountryCode.DE, "DE-TH");
            var isPublicHolidayInTH2019 = DateSystem.IsOfficialPublicHolidayByCounty(new DateTime(2019, 9, 20), CountryCode.DE, "DE-TH");
            var isPublicHolidayInTH2020 = DateSystem.IsOfficialPublicHolidayByCounty(new DateTime(2020, 9, 20), CountryCode.DE, "DE-TH");

            Assert.IsFalse(isPublicHolidayInTH2018);
            Assert.IsTrue(isPublicHolidayInTH2019);
            Assert.IsTrue(isPublicHolidayInTH2020);
        }
```

**Comment by tinohager** [comment]
@Atvaark Can you test again please?

**Comment by Atvaark** [comment]
Hey,

didn't DateSystem.GetPublicHoliday remove holidays that haven't yet existed in the past?

```
        [TestMethod]
        public void TestGermanyGetPublicHolidayWithCountySpecificWorldChildrensDay()
        {
            var worldChildrensDays = DateSystem.GetPublicHoliday(
                    new DateTime(2018, 9, 20),
                    new DateTime(2020, 9, 20),
                    CountryCode.DE)
                .Where(p => p.Name == "World Children's Day")
                .ToList();
            Assert.IsTrue(worldChildrensDays.Any(p => p.Date == new DateTime(2020, 9, 20)));
            Assert.IsTrue(worldChildrensDays.Any(p => p.Date == new DateTime(2019, 9, 20)));
            Assert.IsFalse(worldChildrensDays.Any(p => p.Date == new DateTime(2018, 9, 20))); // Test fails
        }
```


Do the clients have check the **PublicHoliday.LaunchYear** now?

**Comment by tinohager** [comment]
No the method have never remove holidays. The LaunchYear is a experimental feature.
