### ISSUE TITLE
Canadian Errors

### ISSUE THREAD

**Issue by FlaveC** [tinohager/Nager.Date#173]
Three items for Canadian holidays:

1. In CanadaProvider.cs the string for Newfoundland is in German (I think); you have "Neufundland und Labrador" and it should be "Newfoundland and Labrador".

2. Also in CanadaProvider.cs you have Quebec (CA-QC) listed for the June 24th "Discovery Day" holiday. In Quebec this date is actually celebrated as the "Fête nationale du Québec" ("National Holiday" in English). This is actually quite an important holiday for Quebecers. 
https://en.wikipedia.org/wiki/Public_holidays_in_Canada#Quebec

3. Also in CanadaProvider.cs you have two entries for the Yukon (CA-YT) "Discovery Day" holiday, once in June and again in August. The August entry is the correct one. 
https://en.wikipedia.org/wiki/Discovery_Day#Canada

**Comment by tinohager** [comment]
@FlaveC Thanks, i have publish a new version
