### ISSUE TITLE
Germany - May 8th 2020 - "Tag der Befreiung"

### ISSUE THREAD

**Issue by laloune** [tinohager/Nager.Date#175]
Berlin gets a one-time public holiday next year

* DE-BE
* May 8th 2020

See for reference: https://www.feiertage-deutschland.de/tag-der-befreiung/

localName: Tag der Befreiung
name: Liberation day ? (this is not official but this should be the right translation)

**Comment by laloune** [comment]
hello,

will this be reflected in the API ?

thx,

**Comment by tinohager** [comment]
My daughter was born a few days ago, I hope the change still has a little time I will take care of it as soon as I have some air for it again.

**Comment by laloune** [comment]
congrats!!!
there is definitely no hurry.

take care :-)

**Comment by tinohager** [comment]
The api is now updated
