### ISSUE TITLE
Canada Day is incorrect in Alberta 

### ISSUE THREAD

**Issue by haue** [tinohager/Nager.Date#180]
Definition of Canada Day:
July 1, except when it falls on a Sunday, then it is July 2

see: [https://www.alberta.ca/alberta-general-holidays.aspx#toc-7](https://www.alberta.ca/alberta-general-holidays.aspx#toc-7)

**Comment by tinohager** [comment]
Does this mean that the information on Wikipedia is incorrect? https://en.wikipedia.org/wiki/Public_holidays_in_Canada

**Comment by tinohager** [comment]
Affected file: [CanadaProvider.cs](https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/CanadaProvider.cs)

**Comment by tinohager** [comment]
I have fix this problem, can you check it please https://github.com/tinohager/Nager.Date/commit/842eedc6046453b7c22840ab4abb264c57e157c7
