### ISSUE TITLE
Date shifts?

### ISSUE THREAD

**Issue by JoopDeFouw** [tinohager/Nager.Date#181]
The returned dates by the API service and also the results on the website have a -1 day shift.
ie: All New year days are on 31-12. This applies to all countries.
Is this a bug or did i missed something in the documentation explaining this?

![Screenshot](https://user-images.githubusercontent.com/34922752/69915047-01970a80-144b-11ea-8316-72482da992a6.png)

**Comment by tinohager** [comment]
@JoopDeFouw Thank you for the hint, i solved the problem.
