### ISSUE TITLE
LocalName for Presidents Day in US is the official holiday rather than the common name

### ISSUE THREAD

**Issue by carlin-q-scott** [tinohager/Nager.Date#183]
### Important specifications

* Which country is affected? US
* If you have found a mistake please also provide a valid source of your information?
https://grammarist.com/spelling/labor-labour/

For more information, see the `CONTRIBUTING` guide.

### Description

"Labour" Day in the US is spelled "Labor". That is, it does not have a u.

**Comment by tinohager** [comment]
The `LocalName` is 'Labor Day' for this country.

**Comment by carlin-q-scott** [comment]
Oh, I missed that property. Thanks.

**Comment by carlin-q-scott** [comment]
Hmm, well now I have another problem. The LocalName for "Presidents' Day" is "Washington's Birthday", but I've never seen that before in the US. 

According to [federalpay.org](https://www.federalpay.org/holidays/presidents-day), it's colloquially known as "President's Day", but officially it's "Washington's Birthday". Which one should be considered the LocalName? I also notice the apostrophe is in a different place for the common name of the holiday.

**Comment by tinohager** [comment]
The source is https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States

**Comment by tinohager** [comment]
I think we can switch the Localname and name for this date. Is this good for you?

**Comment by carlin-q-scott** [comment]
Yeah, but to what? My guess would be:
Name = "Washington's Birthday",
LocalName = "Presidents Day"

Dropping the apostrophe is propper according to this: https://en.wikipedia.org/wiki/Washington%27s_Birthday#Spelling
