### ISSUE TITLE
GetPublicHoliday method assumes DateTimes are dates

### ISSUE THREAD

**Issue by carlin-q-scott** [tinohager/Nager.Date#184]
### Important specifications

* Which country is affected? All
* If you have found a mistake please also provide a valid source of your information?

### Description
The GetPublicHoliday method does not return the holiday if I provide a startDate that is one second into the holiday. I'd expect any time during the holiday to return the holiday.

I think either the method should use startDate.Date, or there should be some warning in the documentation about the holiday being only exactly at midnight.

**Comment by tinohager** [comment]
Hi, i have push a fix

**Comment by carlin-q-scott** [comment]
Thanks! I checked the code changes and they're perfect.
