### ISSUE TITLE
Long Weekends Month wrong if going to next month

### ISSUE THREAD

**Issue by tknaller** [tinohager/Nager.Date#186]
### Important specifications

* Which country is affected?
Austria
* If you have found a mistake please also provide a valid source of your information?
Screenshot nager.date Homepage:

![Screenshot_2020-01-06-13-40-52-993_com android chrome](https://user-images.githubusercontent.com/25546953/71818837-58b37f00-308a-11ea-9f8e-cdde8349fb15.jpg)

### Description

long weekend has wrong month name if it goes to the next month, see screenshot may 30th + may 31st + may 1st should be june 1st

**Comment by tinohager** [comment]
Thanks i have fix the issue

**Comment by tknaller** [comment]
now it incorrectly shows all three days as june:
![Screenshot_2020-01-06-20-52-27-553_com android chrome](https://user-images.githubusercontent.com/25546953/71844485-87e7e180-30c6-11ea-891b-e02616e678d4.jpg)

i think you should use day as the variable in the line you edited in the last commit instead of longWeekend.something

**Comment by tknaller** [comment]
now it's working awesome, thank you very much!
