### ISSUE TITLE
New public holiday in Croatia - Remembrance Day for Homeland War Victims

### ISSUE THREAD

**Issue by miblazevic** [tinohager/Nager.Date#188]
A new holiday has been added in Croatia this year.
It's called "Remembrance Day for Homeland War Victims" or "Dan sjećanja na žrtve Domovinskog rata" in Croatian.

You can read more about it here:
https://en.wikipedia.org/wiki/Public_holidays_in_Croatia

**Comment by miblazevic** [comment]
Pull request has been created #189

**Comment by tinohager** [comment]
Thanks for the pull
