### ISSUE TITLE
Special territority code used correctly? (ES-IC)

### ISSUE THREAD

**Issue by jbroudou** [tinohager/Nager.Date#192]
Your project uses the code ES-IC at https://github.com/tinohager/Nager.Date/blob/19708096531b93573c967732657b8022240abcc2/Src/Nager.Date/PublicHolidays/SpainProvider.cs#L49

The ISO subdivision codes for Spain are listed at https://en.wikipedia.org/wiki/ISO_3166-2:ES. The ISO subdivision code for Canary Islands is ES-CN (which is not used by your project). On this wikipedia page it is also noted that:

"Special territories
The following two areas not covered by European Union Customs arrangements are also exceptionally reserved ISO 3166-1 alpha-2 codes on the request of the World Customs Organization:

EA Ceuta, Melilla
IC Canary Islands
However, these codes do not correspond in any way to the ISO 3166-2 codes of the territories."

Can you please confirm that you have correctly used the special territory code ES-IC, and it is in fact the holidays listed by your project are not intended to be the holiday of the Spanish subdivision ES-CN (Canary Islands).

**Comment by tinohager** [comment]
I think this is a bug, i fix this. I have check my source https://en.wikipedia.org/wiki/Public_holidays_in_Spain and `ES-CN` is the right one.
