### ISSUE TITLE
Getting a System.ArgumentNullException calling IsOfficialPublicHolidayByCounty

### ISSUE THREAD

**Issue by dannycrone** [tinohager/Nager.Date#22]
Hi Tino,
First of all, just wanted to say this is a great library 🥇 
When I am checking a date that is a holiday for county code "GB-ENG" then I get an exception on items where they do not have any Counties (null). 
{"Value cannot be null.\r\nParameter name: source"}
```        
public static bool IsOfficialPublicHolidayByCounty(DateTime date, CountryCode countryCode, string countyCode)
{
    var items = GetPublicHoliday(countryCode, date.Year);
    return items.Where(o => o.Date.Date == date.Date && o.Counties.Contains(countyCode) && o.CountyOfficialHoliday).Any();
}
```
However, what I really want is to find if a date is a holiday in the UK but exclude any holidays that are specifically for Northern Ireland or Scotland, so I created the following method :
```        
return IsOfficialPublicHolidayExcludeCounties(date, CountryCode.GB, new string[] { "GB-NIR", "GB-SCT" });

public static bool IsOfficialPublicHolidayExcludeCounties(DateTime date, CountryCode countryCode, string[] countyCodes)
{
    var items = DateSystem.GetPublicHoliday(countryCode, date.Year);
    return items.Where(o => o.Date.Date == date.Date && (o.Counties == null || o.Counties.Except(countyCodes).Any()) && o.CountyOfficialHoliday).Any();
}
```
Thought it might help

**Comment by AndrueCope** [comment]
Yup. Just hit this myself.

**Comment by dannycrone** [comment]
I'm not sure I want to change the method as I am not entirely sure of it's intent. I guess we could change the line to:
`return items.Where(o => o.Date.Date == date.Date && o.Counties != null && o.Counties.Contains(countyCode) && o.CountyOfficialHoliday).Any();`

**Comment by AndrueCope** [comment]
Oh I've just pulled those lines into my own code for now. I'm only writing unit tests so for the time being I can just use that instead of calling IsOfficialPublicHolidayByCounty().

**Comment by AndrueCope** [comment]
Lol, and I forgot a set of brackets. Or more correctly ReSharper did. It should be:

 items.Any(o => o.Date.Date == queryTime.Date && **(**(o.Counties==null)||o.Counties.Contains("GB-ENG")**)** && o.CountyOfficialHoliday)

**Comment by tinohager** [comment]
If this issue done?
