### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by stephenlawuk** [tinohager/Nager.Date#3]
Currently if you were in December and also wanted the next months January holidays you would need to get the full current year + next years holidays and filter out all the rest.

It would be useful in the above situation and others to be able to get holidays between two sets of dates. I imagine Month/Year range selection would be most useful but I guess some may want full date range.

**Comment by tinohager** [comment]
Hi

You want a method like that example?

    var startDate = new DateTime(2016, 12, 01);
    var endDate = new DateTime(2017, 2, 28);
    var publicHolidays = DateSystem.GetPublicHoliday("DE", startDate, endDate);

Result the public holidays between december 2016 to february 2017

**Comment by stephenlawuk** [comment]
Hi,

Yes a method like that would be perfect.

**Comment by tinohager** [comment]
Hi, i have add this method in the new version
