### ISSUE TITLE
Veterans Day 2017 US is incorrect

### ISSUE THREAD

**Issue by pkatsourakis-dcu** [tinohager/Nager.Date#48]
For US holidays in 2017 Veterans day is November 11th. This returns November 10th.  Veterans day is wrong for 2018 too. 

Found through http://publicholiday.azurewebsites.net/PublicHoliday/Country/US/2017

**Comment by tinohager** [comment]
The date shift on a weekend. https://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/federal-holidays/#url=2017

    *** November 11, 2017 (the legal public holiday for Veterans Day), falls on a Saturday. For most Federal employees, Friday, November 10, will be treated as a holiday for pay and leave purposes. (See 5 U.S.C. 6103(b).)
