### ISSUE TITLE
Error 403 - This web app is stopped.

### ISSUE THREAD

**Issue by cdestouni** [tinohager/Nager.Date#49]
Hi, 

I was previously using the bank holiday API for my webapp, however as of today I noticed a 403 error. Is this forbidden to all users now?

Cheers

**Comment by tinohager** [comment]
Hi, no it is not forbidden but the free azure account only allow a limited count of requests per day. And the limit for today is reached. Sorry

**Comment by tinohager** [comment]
move the project from azure to a own server
