### ISSUE TITLE
For CountryCode FR the 26/12 is not a public holiday

### ISSUE THREAD

**Issue by masiref** [tinohager/Nager.Date#55]
Hello,

In France the 26/12 is not a public holiday. Can you adapt it please ?

Thanks

**Comment by tinohager** [comment]
I think the right approach is to add `new string[] { "FR-A", "FR-54" }` for 26/12. Is this correct?

https://github.com/tinohager/Nager.Date/blob/master/Src/Nager.Date/PublicHolidays/FranceProvider.cs

**Comment by tinohager** [comment]
i have publish a new version with the fix
