### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by Shaenn** [tinohager/Nager.Date#56]
Hello Tino hager! 
The subject of holidays is very interesting and depth. 
In discovering the commenthol project I found the idea very interesting and I wanted to make a C# dll much more rigid and formal, because I am primarily a software developer. I use their data that I format according to my architecture. 
I have already started to integrate several countries, the work will be long and tedious. 
You did a lot of work on your dll and congratulations! 

Best regards Shaenn!

**Comment by tinohager** [comment]
Thank you, The approaches are very different as we solve the problem. I wish you much success with your project!

**Comment by Shaenn** [comment]
Thank's a lot,

I wish you too much success with your project and the implementation of more complex rule ;-)

Shaenn (https://github.com/Shaenn/ID3iHoliday)

Have a nice evening.
