### ISSUE TITLE
Us Public holidays

### ISSUE THREAD

**Issue by robesonm93** [tinohager/Nager.Date#57]
Hello,
This code snippet:
string output = string.Empty;
var holidays = DateSystem.GetPublicHoliday(CountryCode.US, 2020).ToList();
foreach (var h in holidays)
{
   output += $"{h.Name} - {h.Date.ToString("d")}\n";
 }
output += "\n";

Returns 7/3/2020 as the .Date for Independence Day, not 7/4/2020.

Thank you.

**Comment by tinohager** [comment]
https://archive.opm.gov/Operating_Status_Schedules/fedhol/2020.asp

** July 4, 2020 (the legal public holiday for Independence Day), falls on a Saturday. For most Federal employees, Friday, July 3, will be treated as a holiday for pay and leave purposes. (See 5 U.S.C. 6103(b).)

**wikipedia**
New Year's Day, Independence Day, Veterans Day, and Christmas Day are observed on the same calendar date each year. Holidays that fall on a Saturday are observed by federal employees who work a standard Monday to Friday week on the previous Friday. Federal employees who work on Saturday will observe the holiday on Saturday; Friday will be a regular work day. Holidays that fall on a Sunday are observed by federal workers the following Monday. The other holidays always fall on a particular day of the week.[5]
