### ISSUE TITLE
One holiday too many - SI

### ISSUE THREAD

**Issue by brdnacer** [tinohager/Nager.Date#58]
As also stated in wikipedia article, the _Primož Trubar day_ is not a work-free day in Slovenia (SI), and therefore should not be included in list of holidays.
Line `items.Add(new PublicHoliday(year, 6, 8, "dan Primoža Trubarja", "Primož Trubar Day", countryCode));` should be removed.
Cheers.

**Comment by tinohager** [comment]
i have fix the issue in the next version
