### ISSUE TITLE
Canada Victoria Day and National Patriots' Day Problem

### ISSUE THREAD

**Issue by captainRL** [tinohager/Nager.Date#59]
Hi,

In Canada, Victoria Day and National Patriots' Day are the Monday right **before** May 25th.  

In your algorithm, it's seems to be the first Monday **after** May 25th.

She this page for details: [https://www.statutoryholidays.com/victoriaday.php](https://www.statutoryholidays.com/victoriaday.php)

Both holidays needs to be corrected (Victoria Day and National Patriots' Day).

Thank you.
![public holidays for canada - nager date_2018-01-30_16-30-22](https://user-images.githubusercontent.com/35976190/35592424-f3646e2e-05da-11e8-946c-cb3fe71a555b.png)

**Comment by tinohager** [comment]
I have commit a fix can you check it again?

**Comment by captainRL** [comment]
Problem seems to be fixed now.  Thank you very much for your prompt response!
