### ISSUE TITLE
Missing Easter day

### ISSUE THREAD

**Issue by bacca87** [tinohager/Nager.Date#6]
Why the easter day is missing for all countries that celebrate this day?
Ok, I know that this day is always on sunday, but why not add anyway this holiday?

For example in my application there is a calendar that display all the holidays, but easter is missing and i have to calculate this day by myself.

**Comment by bacca87** [comment]
And why in the SloveniaProvider the Easter day is present?

**Comment by tinohager** [comment]
I use the fnformations from wikipedia the link is in all provider available. The Easter day is not listed as a public holiday
