### ISSUE TITLE
Huge performance issues

### ISSUE THREAD

**Issue by alex-jitbit** [tinohager/Nager.Date#66]
Calling `IsPublicHoliday` in a loop result in terrible performance degradation since all the providers and dictionaries are re-created every time, FROM SCRATCH.

You have to cache them in static vars

**Comment by tinohager** [comment]
I think I do not have to do anything. You can cache the items self.

If you use the project in your software you are welcome to support me. Then I can optimize the query.

**Comment by alex-jitbit** [comment]
We did create a workaround in the calling code, but I thought you and others might know of this issue.

I can fix and send a pull request to you.

PS. Also I don't mind donating to a good project to keep you going, will do that later

**Comment by tinohager** [comment]
Thanks for the pull

**Comment by alex-jitbit** [comment]
please include this in your next nuget release, thanks

**Comment by tinohager** [comment]
is available
