### ISSUE TITLE
Canada Provider check

### ISSUE THREAD

**Issue by tinohager** [tinohager/Nager.Date#69]
The information on Wikipedia differs from the information on the official website.

For example
- Bank holiday – January 2 (Quebec only)

https://www.canada.ca/en/revenue-agency/services/tax/public-holidays.html
https://en.wikipedia.org/wiki/Public_holidays_in_Canada

**Comment by rubenmonteiro** [comment]
I trust more official sites, like the government of Canada then a wikipage

**Comment by tinohager** [comment]
You have submitted your enquiry to Canada.ca, the primary online access point to information on the Government of Canada, its programs and its services. We direct people to relevant information on Canada.ca or on other Government of Canada websites.
Wikipedia is not a Government of Canada website, as such we are not responsible for the accuracy, currency or reliability of the content of such websites.

A statutory holiday is a public holiday established by federal, provincial or territorial statute, on which government and business offices, schools and courts are generally closed.

Statutory holidays legislated by the Government of Canada are observed nationwide. However, in some cases a holiday may only be observed by Government of Canada offices, Crown corporations, federal agencies and businesses under federal jurisdiction. Please contact Employment and Social Development Canada to obtain additional information on federal statutory holidays. Contact information for the Department is accessible from the "Contact Us" section of its Labour Program website at the following URL:

Contact Us
https://www.canada.ca/en/employment-social-development/services/labour-contact.html

Statutory holidays established by provincial or territorial statute are observed in the province or territory where they are legislated.

Please contact the responsible provincial or territorial ministry of labour to obtain information on its established statutory holidays. Contact information for these ministries is accessible from Canada.ca at the following URL:

Employment standards in Canada
https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/after-apply-next-steps/labour-standards-canada.html

Because of the length of the preceding URL, we suggest that you copy and paste it directly into the address bar of your Web browser.

**Comment by tinohager** [comment]
The first result on google is not uptodate 👍 

![image](https://user-images.githubusercontent.com/8215186/37214161-72605ad4-23b4-11e8-96fa-dd5a02a1c42c.png)
