### ISSUE TITLE
Thoughts on library

### ISSUE THREAD

**Issue by karczk** [tinohager/Nager.Date#71]
I was looking for a library (holidays), but none meet my requirements. Finally, I wrote something of my own, but I will leave here a few suggestions/comments. When it comes to functionality, it's a great library, but it has some drawbacks with the model or assumptions.

1. Holiday and holiday occurrence are both in the same model "PublicHoliday". This is broken by definition.

Example:
Christian feast day "Epiphany" is also polish public holiday:
- from X (I didn't find, probably 1952) to 1960 it was a day off
- from 1961 to 2010 it wasn't a day off
- from 2011 is a day off again (btw, Nager.Date returns for each year as public holiday = bug (PolandProvider))

It is not possible to describe it by "LaunchYear" (launched twice ;)), "CountyOfficialHoliday", "CountyAdministrationHoliday" properties.

2. PublicHoliday is mutable class. For me it should be immutable, there is not point to create instance outside library or to mutate it later.

3. Performance is not so great. For example PolandProvider creates list and sort it, which is not needed at all.

4. Missing IEquatable implementation + equality operators.

Quick suggestions:
1. Create immutable class or struct "Holiday", which will describe holiday in general (don't have date property), e.g. New Year's Day. Provide GetOccurrences() for concrete holiday (instance of Holiday), that returns only New Year's Day occurrences. Static method in Holiday should returns all possible occurrences for all possible holidays.

2. Create struct "HolidayOccurrence", which will describe holiday occurrence (has date). Should contains information about if it is a day off. Immutability and IEquatable are must have.

3. GetOccurrences() should not create new list, just multiple yield return statements.

4. New API should make possible to work in perspective of:
- concrete holiday in concrete country: e.g. all occurrence of Easter Sunday
- all occurrences of all holidays in concrete country
- concrete holiday around the world (or Europe etc.)

**Comment by tinohager** [comment]
Hello thanks for the feedback,

Your requirements are very detailed, for most people using this project the current scope is sufficient.
The performance is good from my point of view, the data could also be cached if needed.

The biggest problem with the public holidays is that it is very expensive to collect all the information. For example, Wikipedia does not provide all the information here https://en.wikipedia.org/wiki/Public_holidays_in_Poland
