### ISSUE TITLE
Good Friday in Hungary

### ISSUE THREAD

**Issue by azshu** [tinohager/Nager.Date#72]
### Important specifications
Affected country: HU
1 Error an 1 added holiday in HungaryProvider.cs
### Description

2 changes in HungaryProvider.cs:

/* Change EE to HU */
var countryCode = CountryCode.HU;

/* Added +1 holiday, since 2017 Good Friday is a public holiday in Hungary */
items.Add(new PublicHoliday(easterSunday.AddDays(-2), "Nagypéntek", "Good Friday", countryCode));

Proof: https://en.wikipedia.org/wiki/Public_holidays_in_Hungary

**Comment by tinohager** [comment]
Thank you the new version with the fix is available on nuget
