### ISSUE TITLE
How can I add holidays from my country?

### ISSUE THREAD

**Issue by mauricioribeiro** [tinohager/Nager.Date#8]
Hi everyone,

First of all, thank you for this contribution. It's really useful. However, I'm from Brazil and there is no support for Brazilian holidays. I would like to help to expand the project adding a Brazil Provider. Is it possible? If yes, how I could do that?

Again, thank you :D

**Comment by tinohager** [comment]
Hi
In the folder Nager.Date/PublicHolidays/ you found all provider for supported countries copy one provider. Change the configuration of dates, i have add in all provider the source of the informations.

**Comment by mauricioribeiro** [comment]
Hi @tinohager, I forked and created BrazilProvider with official holidays. What I have to do now?

**Comment by tinohager** [comment]
Now you must start a pull request. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by mauricioribeiro** [comment]
Thank you @tinohager :)

**Comment by tinohager** [comment]
I have publish a new nuget package with brazil and peru
