### ISSUE TITLE
Canada May 21, 2018

### ISSUE THREAD

**Issue by pedropanpedro** [tinohager/Nager.Date#80]
Using the following
\packages\Nager.Date.1.12.0\lib\net45\Nager.Date.dll

Demonstration of the problem
?  DateSystem.IsPublicHoliday(new DateTime(2018, 05, 21), CountryCode.CA)
false

Confirming it's working
?  DateSystem.IsPublicHoliday(new DateTime(2018, 04, 23), CountryCode.CA)
true
?  DateSystem.IsPublicHoliday(new DateTime(2018, 04, 24), CountryCode.CA)
false

http://date.nager.at/api/v1/get/CA/2018
Shows holiday as there

<PublicHoliday>
<Counties xmlns:d3p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
<d3p1:string>CA-AB</d3p1:string>
<d3p1:string>CA-BC</d3p1:string>
<d3p1:string>CA-MB</d3p1:string>
<d3p1:string>CA-NB</d3p1:string>
<d3p1:string>CA-NT</d3p1:string>
<d3p1:string>CA-NS</d3p1:string>
<d3p1:string>CA-NU</d3p1:string>
<d3p1:string>CA-ON</d3p1:string>
<d3p1:string>CA-PE</d3p1:string>
<d3p1:string>CA-SK</d3p1:string>
<d3p1:string>CA-YT</d3p1:string>
</Counties>
<CountryCode>CA</CountryCode>
<CountyAdministrationHoliday>true</CountyAdministrationHoliday>
<CountyOfficialHoliday>true</CountyOfficialHoliday>
<Date>2018-05-21</Date>
<Fixed>false</Fixed>
<Global>false</Global>
<LaunchYear i:nil="true"/>
<LocalName>Victoria Day</LocalName>
<Name>Victoria Day</Name>
</PublicHoliday>

**Comment by pedropanpedro** [comment]
I updated to latest version 1.20.1. Holiday is now there. How does update process work / how often do I have to update to obtain latest holidays?

**Comment by tinohager** [comment]
The nuget package contains all information in the library. On every update you must load the new package from nuget. The webapi have always the newest informations but is slower and not always available.
