### ISSUE TITLE
"Mariä Himmelfahrt" incorrectly not a holiday in catholic districts of Bavaria/Germany

### ISSUE THREAD

**Issue by jbattermann** [tinohager/Nager.Date#83]
### Important specifications

* Which country is affected? **Germany**
* If you have found a mistake please also provide a valid source of your information?
**Here in Bavaria districts with primarily catholic residents also have the public holiday "Mariä Himmelfahrt" (see the [official government website for details](https://www.statistik.bayern.de/statistik/bevoelkerungsstand/00141.php)), however the [Germany holiday provider only specifies it for 'Saarland'](https://github.com/tinohager/Nager.Date/blob/e97c73f5394fab3e8402bd39133477fc013e08ca/Src/Nager.Date/PublicHolidays/GermanyProvider.cs#L50) (DE-SL) currently.**

### Description

I am not sure whether such district/region specific holidays within a county are currently support in Nager.Date at all otherwise I would have submitted a fix / -PR already :-/

**Comment by jbattermann** [comment]
Yes but that's for 'Saarland' (DE-SL). In 'Bayern' (DE-BY) it is a public holiday for some districts / only in catholic ones. So if you are in a catholic district & using in "DE-BY", Nager.Date does not provide _all_ Public Holidays, hence the question/issue...

**Comment by tinohager** [comment]
It is only possible if germany have more iso codes for this districts.

In france departments are available but i don't can find the same for germany
https://en.wikipedia.org/wiki/ISO_3166-2:FR#Departments
