### ISSUE TITLE
France's special public holidays

### ISSUE THREAD

**Issue by laloune** [tinohager/Nager.Date#84]
Hi,

first a HUGE thank you for your awesome work.

for France there seems to be a mistake : the 2 special public holiday days (Good friday and St. Stephen's day) are in the region Alsace (FR-A I guess) and in the _département_ of the Moselle, which is not FR-54 but FR-57

The wikipedia page states "Alsace-Lorraine" but this is not true, this is "Alsace-Moselle".

**Comment by tinohager** [comment]
Hi, can you fix this information on wikipedia? Have we an other source to check your change?
Thanks

**Comment by laloune** [comment]
Actually the English page of Wikipedia differs from the French one. The French one states : 
"2 jours avant Pâques : Le Vendredi saint, le 10 avril 2009 et le 2 avril 2010 (férié en Alsace et en Moselle)."
https://fr.wikipedia.org/wiki/F%C3%AAtes_et_jours_f%C3%A9ri%C3%A9s_en_France

The English one states : "Friday before Easter Sunday. Alsace and Lorraine only."
https://en.wikipedia.org/wiki/Public_holidays_in_France
=> I corrected it

Finally the official law : https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006902635&cidTexte=LEGITEXT000006072050

**Comment by laloune** [comment]
sorry, the same for St Stephen's day, same law article

**Comment by tinohager** [comment]
Thank you, i update the code the next days...

**Comment by tinohager** [comment]
@laloune Is this now good https://github.com/tinohager/Nager.Date/commit/851f4f9c93a4b1737423e2efb15f886ac83847d7?

**Comment by tinohager** [comment]
@laloune can you check my changes?

**Comment by laloune** [comment]
Hello,

yes, confirmed. Thanks a lot!

**Comment by tinohager** [comment]
i have push a new nuget package
