### ISSUE TITLE
Opening Github project URL is annoying

### ISSUE THREAD

**Issue by TomyCesaille** [tinohager/Nager.Date#85]
Hi Team,
The **Nager.Date/Src/Nager.Date/Install.ps1** script is very annoying as it opens one browser tab for every projects that use the Nager.Date package.

I know marketing is important; This is actually a good idea to redirect devs here but this is intrusive when you have to close 30+ tabs after a solution nuget update/restore.
I also suspect that this is not cool for CI agents either.

I suggests to remove it or to change it for a big ASCII art in the output console.

Regards guys, 
The package itself is awesome 👍

**Comment by tinohager** [comment]
Why you install the package in 30 projects?  For what do you use the library in your projects?

**Comment by TomyCesaille** [comment]
I use it for the calendar holidays feature and I got this package as dependency for an agent framework.
There is a lot of solutions to fix this; I could fork the projects etc.. But I wanted to share my experience.
